### ISSUE TITLE
Finding the file list

### ISSUE THREAD

**Issue by llm96** [mon/sv3c_decrypt#1]
Sorry for posting this as an issue, I'm not sure where else to ask about this kind of stuff.

I'm really curious as to how you were able to narrow down and find [every file here](https://github.com/mon/sv3c_decrypt/blob/master/filelist.txt).

I'm currently trying to do something similar with the 2,100~ files in the new version of INFINITAS but I'm not sure where to start looking. I've briefly checked some AVS file open calls, and can see the regular filename turning into the encrypted one on disk:

```
/data/info/downloadlist.xml
/mnt/edrm/1/crc//info/downloadlist.xml
/mnt/edrm/1/came//info/downloadlist.xml
/mnt/edrm/1/hashed/info/downloadlist.xml
/x/4/1/e/4d19e6c2c64a6b3829fe1932fa5e68e6ef985b60
```

...which matches up with the entry in the `getResourceInfo` network response...

```xml
<file>
  <path __type="str">game/x/4/1/e/4d19e6c2c64a6b3829fe1932fa5e68e6ef985b60</path>
  <version __type="s32">2021090800</version>
  <size __type="s32">540101</size>
  <sum __type="str">97a14924a4da13380bab8f9d2ee19bb6b5471c608058239eb5ee5f758f54cae5</sum>
  <url __type="str">http://atnrsc.konaminet.jp/atn/bm2dx/infinitas/v2/installdata/2021090800/game/x/4/1/e/4d19e6c2c64a6b3829fe1932fa5e68e6ef985b60</url>
</file>
```

But I guess there's no way to turn these obfuscated filenames into regular ones. 😅 

Just watching open calls for filenames could work but I'm worried about missing something.

**Comment by mon** [comment]
SDVX cloud names were reversed using a combination of brute-forcing algorithm (based on stuff like jacket paths), binary analysis, and arcade file lists. It took me upwards of a month to think of every reasonable combination to get them all.

infinitas' new update uses a different system which does not require this method. I can't explain much further than that, sorry.
